// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_3TKpvfqWYi0NANPzGmfcneWwiNYkSNU',
    appId: '1:1058502011871:web:b4c6e3cd64c9641054b26a',
    messagingSenderId: '1058502011871',
    projectId: 'learn-2c3b3',
    authDomain: 'learn-2c3b3.firebaseapp.com',
    storageBucket: 'learn-2c3b3.appspot.com',
    measurementId: 'G-537VW54PCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_nmeA40MyI1J1lGlylsmOUK_4_pa0fo',
    appId: '1:1058502011871:android:5a8c080b79a6cc0e54b26a',
    messagingSenderId: '1058502011871',
    projectId: 'learn-2c3b3',
    storageBucket: 'learn-2c3b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw_vNvOke2QM5DVDjjcADav9Ie78oC_44',
    appId: '1:1058502011871:ios:3c22dc9dbe3b94b354b26a',
    messagingSenderId: '1058502011871',
    projectId: 'learn-2c3b3',
    storageBucket: 'learn-2c3b3.appspot.com',
    iosClientId: '1058502011871-922bbcdlqrn98p0eaj1imvkfr2g94hkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw_vNvOke2QM5DVDjjcADav9Ie78oC_44',
    appId: '1:1058502011871:ios:3c22dc9dbe3b94b354b26a',
    messagingSenderId: '1058502011871',
    projectId: 'learn-2c3b3',
    storageBucket: 'learn-2c3b3.appspot.com',
    iosClientId: '1058502011871-922bbcdlqrn98p0eaj1imvkfr2g94hkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
